version: "3"

services:
  fastapi-app:
    build:
      context: .
    volumes:
      - ./compressed_images:/app/compressed_images
    ports:
      - "8000:8000"
    command:
      ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
